### ISSUE TITLE
When using tools based on TCP connections, some error occurs.

### ISSUE THREAD

**Issue by dqx-eterning** [droidrun/droidrun#129]
The following is the error message.

1.It happens in the take_screenshot method.
```
20:46:30 ERROR: ❌ Error during DroidAgent execution: Error in step 'handle_llm_input': Error taking screenshot: Failed to decode screenshot response: argument should be a bytes-like object or ASCII string, not 'dict'
20:46:30 ERROR: Traceback (most recent call last):
  File "D:\XXXX\droidrun\droidrun\tools\adb.py", line 668, in take_screenshot
    image_bytes = base64.b64decode(tcp_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\XXX\python3.11.9\Lib\base64.py", line 83, in b64decode
    s = _bytes_from_decode_data(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\XXX\python3.11.9\Lib\base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'dict'
```
2.Text input is not working, and there are no detailed logs; it seems to occur in the APK.

**Comment by Timo972** [comment]
The next portal version backing tcp transport isn't released yet. I just triggered a new release for it: v0.3.2

**Comment by Timo972** [comment]
Everything should be working flawlessly on latest main [a9724bd](https://github.com/droidrun/droidrun/commit/a9724bd7235e69081e08727ab0b7717a7cafccf4) with portal v0.3.2.
Let me know how it goes

**Comment by Ethan77-d** [comment]
Sorry, I accidentally clicked close...
Thank you for your reply, but the same error still exists. What I want to say is that when I was verifying yesterday, I built the package based on the latest apk code, and there was no problem with tcp communication because ping and get_state ran normally. The only issue was with the screenshot function. In addition, it seems that AdbDevice does not have the forward_remove method.

**Comment by Timo972** [comment]
I fixed the screenshot + forward_remove issue in commit [a9724bd](https://github.com/droidrun/droidrun/commit/a9724bd7235e69081e08727ab0b7717a7cafccf4). 
But it's only in main branch and hasn't been released on pypi yet.

**Comment by johnmalek312** [comment]
I was looking into the issue, the latest commit fixed the screenshot issue. There is still a bug preventing droidrun keyboard from working `│ DEBUG droidrun-tools Keyboard input TCP response: 200, error: DroidrunKeyboardIME not active or available                │`

**Comment by johnmalek312** [comment]
Disabled tcp keyboard for now, until we figure out how we can activate droidrun keyboard from the apk.

**Comment by sleynsol** [comment]
Keyboard can't be activated through the apk @johnmalek312 
We either always need it to set it as default for a run or have to switch it every time when text will be inputted via adb.

**Comment by sleynsol** [comment]
Fixed with:

[always setup droidrun keyboard as default before running agent ](https://github.com/droidrun/droidrun/commit/78a1a58ff832d49ae8b286918d622e9bdd89f5c1)

[fix: getting phone state via content provider](https://github.com/droidrun/droidrun/commit/17bafa61f09e2ef426d33c139d8310df09e81b12)

[add tcp support for getting screenshots](https://github.com/droidrun/droidrun/commit/e1bb0e70aa608231fc4fc9bf645db9eedf1c9fa8)
